### ISSUE TITLE
Explore text alignment of "Case Studies" header

### ISSUE THREAD

**Issue by dariusbaker** [dariusbaker/tuf-2020-main-site#42]
As raised in slide 23 of the [review deck](https://drive.google.com/open?id=16pThtGVu3b-86QzASEqCpjEbWHsldrkE), the header should look like:
```
Case
 Studies
```

**Comment by kencanak** [comment]
@dariusbaker , did a dirty fix on this. not sure if you are okay with the approach

**Comment by dariusbaker** [comment]
This is good enough for me.
