### ISSUE TITLE
Implement particle system

### ISSUE THREAD

**Issue by dariusbaker** [dariusbaker/tuf-2020-main-site#45]
Particle hovering:
https://jsbin.com/vimediz/edit?css,output

Positioning/generation logic:
https://jsbin.com/xodekin/edit?js,output

Assets:
`/src/img/particles`

As discussed:
Add the images as templates in the markup, then clone them using a controlled-random algorithm.

**Comment by kencanak** [comment]
@darius, implemented the logic, please check.
