### ISSUE TITLE
Button rollover glitch

### ISSUE THREAD

**Issue by dariusbaker** [dariusbaker/tuf-2020-main-site#61]
Unpredictable and irreproducible glitch (sometimes it happens, sometimes it doesn't):
[Screen recording](https://drive.google.com/open?id=1BBkve1UHf3F3SRckvZM6U9A12IKAhz58)
![WhatsApp Image 2020-04-14 at 22 02 14](https://user-images.githubusercontent.com/19809585/79292616-2379c100-7f04-11ea-8f74-f05b48254e7e.jpeg)

**Comment by kencanak** [comment]
set !important rule on border-radius style, see if it fix the issue
